### ISSUE TITLE
using umask in config does not work

### ISSUE THREAD

**Issue by mickeyjohn** [tyzhnenko/AutoMySQLBackup-mydumper#3]
Hi,
Thanks for making this automated script. I need to set permissions the created files so they can be copied for backup later. Currently, dump database files are created with "-rw------- 1 root root" permission. Does any know how to customise the file permissions or why using "umask 022" within the config file do not work?

Regards.
John

**Comment by tyzhnenko** [comment]
@mickeyjohn it seems the script has a typo.
I pushed a new commit. Take a look please and check please

**Comment by mickeyjohn** [comment]
@tyzhnenko Thanks for updating. It seems work now. ;)
